[[CImGuiPack]]
arch = "aarch64"
git-tree-sha1 = "69325b3fd9fe25ccc57fcc12520be37ad17043e9"
os = "macos"

    [[CImGuiPack.download]]
    sha256 = "5fde6dac23f4395b6f863f52f51b6c78bb51e3bf0c963df0fa53e212093a12d8"
    url = "https://github.com/JuliaBinaryWrappers/CImGuiPack_jll.jl/releases/download/CImGuiPack-v0.1.2+0/CImGuiPack.v0.1.2.aarch64-apple-darwin.tar.gz"
[[CImGuiPack]]
arch = "aarch64"
git-tree-sha1 = "dec58a6d9e7af60b1619ed3358e5a18b804df7e0"
libc = "glibc"
os = "linux"

    [[CImGuiPack.download]]
    sha256 = "48eac59254cc79b9ace334aedac39dde09eb155aefbcd02bd19cbf94d723b8ec"
    url = "https://github.com/JuliaBinaryWrappers/CImGuiPack_jll.jl/releases/download/CImGuiPack-v0.1.2+0/CImGuiPack.v0.1.2.aarch64-linux-gnu.tar.gz"
[[CImGuiPack]]
arch = "aarch64"
git-tree-sha1 = "28f15a65da580f9276d303aeee73d6564ec36f24"
libc = "musl"
os = "linux"

    [[CImGuiPack.download]]
    sha256 = "65525ff8939ddb2eb6a35c30bc87a5b82fd648edacdab186e86aa4984ff29f7a"
    url = "https://github.com/JuliaBinaryWrappers/CImGuiPack_jll.jl/releases/download/CImGuiPack-v0.1.2+0/CImGuiPack.v0.1.2.aarch64-linux-musl.tar.gz"
[[CImGuiPack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "71ff1d971c1ac20e3986d385d1692b5046ae2752"
libc = "glibc"
os = "linux"

    [[CImGuiPack.download]]
    sha256 = "fbf88a854f6bded4ee46a55604083047d7201e694e75386b147a4aeb874e617a"
    url = "https://github.com/JuliaBinaryWrappers/CImGuiPack_jll.jl/releases/download/CImGuiPack-v0.1.2+0/CImGuiPack.v0.1.2.armv6l-linux-gnueabihf.tar.gz"
[[CImGuiPack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0d0bb2e2cf4f1a44ecf5b07d4087b76073aeb655"
libc = "musl"
os = "linux"

    [[CImGuiPack.download]]
    sha256 = "19014b3a88ec851e6fa8aa3f36d1e238f56a130c0dd69af826c5db5c50a81fc7"
    url = "https://github.com/JuliaBinaryWrappers/CImGuiPack_jll.jl/releases/download/CImGuiPack-v0.1.2+0/CImGuiPack.v0.1.2.armv6l-linux-musleabihf.tar.gz"
[[CImGuiPack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ea9c45ed029d970ab21d4b65bb989302f38d84c9"
libc = "glibc"
os = "linux"

    [[CImGuiPack.download]]
    sha256 = "9bfa52f947801063e27ce2c77b1f8f6f0386c902dde8bc626d661ef01fb422b6"
    url = "https://github.com/JuliaBinaryWrappers/CImGuiPack_jll.jl/releases/download/CImGuiPack-v0.1.2+0/CImGuiPack.v0.1.2.armv7l-linux-gnueabihf.tar.gz"
[[CImGuiPack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d208596d99470977698804cee1764e1a910b355e"
libc = "musl"
os = "linux"

    [[CImGuiPack.download]]
    sha256 = "523d8ef72f106b7ddb9a1a8c83aeb7ef0fea7eb4ef8b71eeb881dc442014b672"
    url = "https://github.com/JuliaBinaryWrappers/CImGuiPack_jll.jl/releases/download/CImGuiPack-v0.1.2+0/CImGuiPack.v0.1.2.armv7l-linux-musleabihf.tar.gz"
[[CImGuiPack]]
arch = "i686"
git-tree-sha1 = "5229689bfa66c545ef1160debef3fa98ce4ea564"
libc = "glibc"
os = "linux"

    [[CImGuiPack.download]]
    sha256 = "6baeaa895c880fbdef73baf0b65f267c8d0f0e2f0729df5df3702ccf23aa0172"
    url = "https://github.com/JuliaBinaryWrappers/CImGuiPack_jll.jl/releases/download/CImGuiPack-v0.1.2+0/CImGuiPack.v0.1.2.i686-linux-gnu.tar.gz"
[[CImGuiPack]]
arch = "i686"
git-tree-sha1 = "7e223fb712b7610c0955805dd3eef57cf2b035ee"
libc = "musl"
os = "linux"

    [[CImGuiPack.download]]
    sha256 = "6eb6e724a2c31cebc0a39d9a45c7bb39f810ca5f886a08b3fd23044cc3d524f1"
    url = "https://github.com/JuliaBinaryWrappers/CImGuiPack_jll.jl/releases/download/CImGuiPack-v0.1.2+0/CImGuiPack.v0.1.2.i686-linux-musl.tar.gz"
[[CImGuiPack]]
arch = "i686"
git-tree-sha1 = "c34fd7755dcf43e76d10175a15dfe61c2c98e3b4"
os = "windows"

    [[CImGuiPack.download]]
    sha256 = "ab2b231668f8872105bf89d8ca5a41fc5713d480ff0fabd255d090f67e976541"
    url = "https://github.com/JuliaBinaryWrappers/CImGuiPack_jll.jl/releases/download/CImGuiPack-v0.1.2+0/CImGuiPack.v0.1.2.i686-w64-mingw32.tar.gz"
[[CImGuiPack]]
arch = "powerpc64le"
git-tree-sha1 = "3201f440bcc6c5408e2323fd86df05ec625dc0ee"
libc = "glibc"
os = "linux"

    [[CImGuiPack.download]]
    sha256 = "20787fb97096a532187fbb967b8222b8cb3a6fad4544cd4c21a15894d20c4ab5"
    url = "https://github.com/JuliaBinaryWrappers/CImGuiPack_jll.jl/releases/download/CImGuiPack-v0.1.2+0/CImGuiPack.v0.1.2.powerpc64le-linux-gnu.tar.gz"
[[CImGuiPack]]
arch = "x86_64"
git-tree-sha1 = "c5928e2afb0ec6548ecaa93d99295a6a10306a26"
os = "macos"

    [[CImGuiPack.download]]
    sha256 = "c91b13b1a0293769fc022b89529f4470031a690c97b06a6e57b9ffe91a2965c5"
    url = "https://github.com/JuliaBinaryWrappers/CImGuiPack_jll.jl/releases/download/CImGuiPack-v0.1.2+0/CImGuiPack.v0.1.2.x86_64-apple-darwin.tar.gz"
[[CImGuiPack]]
arch = "x86_64"
git-tree-sha1 = "6e41f7d5f316e6213feb9f44431dfca2e41f9ac3"
libc = "glibc"
os = "linux"

    [[CImGuiPack.download]]
    sha256 = "42ffa9da3cded396446805181cf47c5e89479b825ff126def8918c71cc32fcde"
    url = "https://github.com/JuliaBinaryWrappers/CImGuiPack_jll.jl/releases/download/CImGuiPack-v0.1.2+0/CImGuiPack.v0.1.2.x86_64-linux-gnu.tar.gz"
[[CImGuiPack]]
arch = "x86_64"
git-tree-sha1 = "9e3e95445ed54cbfc6f864cf8847a18c59f64ece"
libc = "musl"
os = "linux"

    [[CImGuiPack.download]]
    sha256 = "5bd25d143e1ec2d870a2342beee20a1d7e58a5139bda1e3cddb8ce7912486a8a"
    url = "https://github.com/JuliaBinaryWrappers/CImGuiPack_jll.jl/releases/download/CImGuiPack-v0.1.2+0/CImGuiPack.v0.1.2.x86_64-linux-musl.tar.gz"
[[CImGuiPack]]
arch = "x86_64"
git-tree-sha1 = "4a7e494d037844e17b41c900a0cff0bb27b4d89d"
os = "freebsd"

    [[CImGuiPack.download]]
    sha256 = "72d80ca8494b75456b75bb9946940139af6f52b491eb89f8d2933e491c935aa0"
    url = "https://github.com/JuliaBinaryWrappers/CImGuiPack_jll.jl/releases/download/CImGuiPack-v0.1.2+0/CImGuiPack.v0.1.2.x86_64-unknown-freebsd.tar.gz"
[[CImGuiPack]]
arch = "x86_64"
git-tree-sha1 = "332c8d1e20d65e18db01d6e29164ca87a9d83cb0"
os = "windows"

    [[CImGuiPack.download]]
    sha256 = "87e1fc7cfac2c593c936d1e1f9083b29c8b2a0c3df87d0b64e26edf55fd9ef5c"
    url = "https://github.com/JuliaBinaryWrappers/CImGuiPack_jll.jl/releases/download/CImGuiPack-v0.1.2+0/CImGuiPack.v0.1.2.x86_64-w64-mingw32.tar.gz"
