[[CImGuiPack]]
arch = "aarch64"
git-tree-sha1 = "27e973e5cb4ea401757a75a4e531489c35fbea5f"
os = "macos"

    [[CImGuiPack.download]]
    sha256 = "2a9d7b3e44800167de9b1d6ba7cffc7d631abdaf3e74beaf625ab052a4b71d12"
    url = "https://github.com/JuliaBinaryWrappers/CImGuiPack_jll.jl/releases/download/CImGuiPack-v0.9.0+0/CImGuiPack.v0.9.0.aarch64-apple-darwin.tar.gz"
[[CImGuiPack]]
arch = "aarch64"
git-tree-sha1 = "da2521e9424aa3cba5a198af30c8df00aefbac1a"
libc = "glibc"
os = "linux"

    [[CImGuiPack.download]]
    sha256 = "5d926f683218b04810da514add332ba090dd888332f1b2aaaf054810060f2180"
    url = "https://github.com/JuliaBinaryWrappers/CImGuiPack_jll.jl/releases/download/CImGuiPack-v0.9.0+0/CImGuiPack.v0.9.0.aarch64-linux-gnu.tar.gz"
[[CImGuiPack]]
arch = "aarch64"
git-tree-sha1 = "28f470b02ef54899a2acc6633ba2a48a6281cbbb"
libc = "musl"
os = "linux"

    [[CImGuiPack.download]]
    sha256 = "0bb72d3a1dd0709f86364f904555f23c72af4c06d0c6e883e4eef5209e8ea1ed"
    url = "https://github.com/JuliaBinaryWrappers/CImGuiPack_jll.jl/releases/download/CImGuiPack-v0.9.0+0/CImGuiPack.v0.9.0.aarch64-linux-musl.tar.gz"
[[CImGuiPack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7c0b5ada0aba818885a62c7d258c77dce23e1c0d"
libc = "glibc"
os = "linux"

    [[CImGuiPack.download]]
    sha256 = "cf19fb1cef7f26087aea2decdabf3aa4e38c1383b0276d48acec3e9b924b32bf"
    url = "https://github.com/JuliaBinaryWrappers/CImGuiPack_jll.jl/releases/download/CImGuiPack-v0.9.0+0/CImGuiPack.v0.9.0.armv7l-linux-gnueabihf.tar.gz"
[[CImGuiPack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "585508d8584630d7f8b9940c3aa3d396703ef156"
libc = "musl"
os = "linux"

    [[CImGuiPack.download]]
    sha256 = "b5c31f553fedb1517870fb9baf2b85a60655144b9fecf7566c1b8d0167f53795"
    url = "https://github.com/JuliaBinaryWrappers/CImGuiPack_jll.jl/releases/download/CImGuiPack-v0.9.0+0/CImGuiPack.v0.9.0.armv7l-linux-musleabihf.tar.gz"
[[CImGuiPack]]
arch = "i686"
git-tree-sha1 = "866833ebf6cc0b0cc55bce0173ecc299727ad441"
libc = "glibc"
os = "linux"

    [[CImGuiPack.download]]
    sha256 = "a8039c286cbf5b46495cc9fac421fe935289fe0acf4d3a608ad747510ecf0284"
    url = "https://github.com/JuliaBinaryWrappers/CImGuiPack_jll.jl/releases/download/CImGuiPack-v0.9.0+0/CImGuiPack.v0.9.0.i686-linux-gnu.tar.gz"
[[CImGuiPack]]
arch = "i686"
git-tree-sha1 = "4657b833b40037a69212c6c0ac68d7371e4531c6"
libc = "musl"
os = "linux"

    [[CImGuiPack.download]]
    sha256 = "03e032558026e28a98ae3b77840a0f741349dea52388b3e15665af03e4fb711a"
    url = "https://github.com/JuliaBinaryWrappers/CImGuiPack_jll.jl/releases/download/CImGuiPack-v0.9.0+0/CImGuiPack.v0.9.0.i686-linux-musl.tar.gz"
[[CImGuiPack]]
arch = "i686"
git-tree-sha1 = "a625698d797fba77adb78fa569b95991e23a5e01"
os = "windows"

    [[CImGuiPack.download]]
    sha256 = "841d4469bd6ad1d170458f407e9e02eb187a90cf8d3dd4acf021140209aedd4c"
    url = "https://github.com/JuliaBinaryWrappers/CImGuiPack_jll.jl/releases/download/CImGuiPack-v0.9.0+0/CImGuiPack.v0.9.0.i686-w64-mingw32.tar.gz"
[[CImGuiPack]]
arch = "powerpc64le"
git-tree-sha1 = "0bc74e23118d8541db546e97f2352243bcb92b09"
libc = "glibc"
os = "linux"

    [[CImGuiPack.download]]
    sha256 = "ea6d23d39f3f7a2edfbb3f40784d3bb58c8d166a1d48d80447f16235353bc57b"
    url = "https://github.com/JuliaBinaryWrappers/CImGuiPack_jll.jl/releases/download/CImGuiPack-v0.9.0+0/CImGuiPack.v0.9.0.powerpc64le-linux-gnu.tar.gz"
[[CImGuiPack]]
arch = "x86_64"
git-tree-sha1 = "bedf78199419b4a0e5e4973df08fc71260eb5fa6"
os = "macos"

    [[CImGuiPack.download]]
    sha256 = "33b0bba41edec5b359f6520afc895bed615332993ff2cf4f7201526124083bb0"
    url = "https://github.com/JuliaBinaryWrappers/CImGuiPack_jll.jl/releases/download/CImGuiPack-v0.9.0+0/CImGuiPack.v0.9.0.x86_64-apple-darwin.tar.gz"
[[CImGuiPack]]
arch = "x86_64"
git-tree-sha1 = "48e7d3dcb20249c89812cdf8915aa356f3472673"
libc = "glibc"
os = "linux"

    [[CImGuiPack.download]]
    sha256 = "14b6d4a635e56a34e18d3c50e8a98cd63c22da3ac319a8ac9ab8e963099ea528"
    url = "https://github.com/JuliaBinaryWrappers/CImGuiPack_jll.jl/releases/download/CImGuiPack-v0.9.0+0/CImGuiPack.v0.9.0.x86_64-linux-gnu.tar.gz"
[[CImGuiPack]]
arch = "x86_64"
git-tree-sha1 = "7d62c952162fd268764b65f816c95cab5c8cb156"
libc = "musl"
os = "linux"

    [[CImGuiPack.download]]
    sha256 = "847f8fc263c835fdc8c2b1fbd96b3674d02737f3b2c98645bca5eaf4791e4824"
    url = "https://github.com/JuliaBinaryWrappers/CImGuiPack_jll.jl/releases/download/CImGuiPack-v0.9.0+0/CImGuiPack.v0.9.0.x86_64-linux-musl.tar.gz"
[[CImGuiPack]]
arch = "x86_64"
git-tree-sha1 = "805641adf85afa1e2f1d84d5b84b5868b31b954f"
os = "freebsd"

    [[CImGuiPack.download]]
    sha256 = "37cf86ed6c0be44c1fb0db6c3af01aa8f17dc9897519f8a95a974ba486c560e6"
    url = "https://github.com/JuliaBinaryWrappers/CImGuiPack_jll.jl/releases/download/CImGuiPack-v0.9.0+0/CImGuiPack.v0.9.0.x86_64-unknown-freebsd.tar.gz"
[[CImGuiPack]]
arch = "x86_64"
git-tree-sha1 = "e7a59fc7a4b7537d74e9533aa0b946a50091b737"
os = "windows"

    [[CImGuiPack.download]]
    sha256 = "0610db4e2e51ee472ff2e96429b76890010cd8432c6373ad47d759b218dbc0cd"
    url = "https://github.com/JuliaBinaryWrappers/CImGuiPack_jll.jl/releases/download/CImGuiPack-v0.9.0+0/CImGuiPack.v0.9.0.x86_64-w64-mingw32.tar.gz"
