[[CImGuiPack]]
arch = "aarch64"
git-tree-sha1 = "a7414526858cca223d2117a1f0f56cc53a971a5d"
os = "macos"

    [[CImGuiPack.download]]
    sha256 = "ccb9ccacfcd933d881f48992087b57865aec1eb8f8d32790605ee8d61f768dd9"
    url = "https://github.com/JuliaBinaryWrappers/CImGuiPack_jll.jl/releases/download/CImGuiPack-v0.12.2+0/CImGuiPack.v0.12.2.aarch64-apple-darwin.tar.gz"
[[CImGuiPack]]
arch = "aarch64"
git-tree-sha1 = "f5ed111652c504cda6159bd5f3422754f491580d"
libc = "glibc"
os = "linux"

    [[CImGuiPack.download]]
    sha256 = "1dcba3f994448bfb2567b5c6ae68de54ee08e123ae2b864d820e7acc885017be"
    url = "https://github.com/JuliaBinaryWrappers/CImGuiPack_jll.jl/releases/download/CImGuiPack-v0.12.2+0/CImGuiPack.v0.12.2.aarch64-linux-gnu.tar.gz"
[[CImGuiPack]]
arch = "aarch64"
git-tree-sha1 = "871b4ffa554349f5480b9ea97971b7ac50c538dc"
libc = "musl"
os = "linux"

    [[CImGuiPack.download]]
    sha256 = "bdb540942f6c40989f138a180b1abc0fd29485f55c3b1b6f0568fe7cbc55eb84"
    url = "https://github.com/JuliaBinaryWrappers/CImGuiPack_jll.jl/releases/download/CImGuiPack-v0.12.2+0/CImGuiPack.v0.12.2.aarch64-linux-musl.tar.gz"
[[CImGuiPack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "26639843a03eee40d03444b610f12f367a64cdd5"
libc = "glibc"
os = "linux"

    [[CImGuiPack.download]]
    sha256 = "3d09f6771c74863a96e73718019caf34c360ff51db779f4ef1d03bf48de64e63"
    url = "https://github.com/JuliaBinaryWrappers/CImGuiPack_jll.jl/releases/download/CImGuiPack-v0.12.2+0/CImGuiPack.v0.12.2.armv7l-linux-gnueabihf.tar.gz"
[[CImGuiPack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "17d54848118b5edb110994ff6522298b7ae0f530"
libc = "musl"
os = "linux"

    [[CImGuiPack.download]]
    sha256 = "87e95b5e18402bd182ee0958f33c70771f7c30d3bb086ce80c506b47268d8706"
    url = "https://github.com/JuliaBinaryWrappers/CImGuiPack_jll.jl/releases/download/CImGuiPack-v0.12.2+0/CImGuiPack.v0.12.2.armv7l-linux-musleabihf.tar.gz"
[[CImGuiPack]]
arch = "i686"
git-tree-sha1 = "901eb7fc5f2956a1602d629fbd059f216fdf7c01"
libc = "glibc"
os = "linux"

    [[CImGuiPack.download]]
    sha256 = "2ba9271dacdfea86d1cb3e318c8a9cca5098be89d965c014462f074563bb8d3e"
    url = "https://github.com/JuliaBinaryWrappers/CImGuiPack_jll.jl/releases/download/CImGuiPack-v0.12.2+0/CImGuiPack.v0.12.2.i686-linux-gnu.tar.gz"
[[CImGuiPack]]
arch = "i686"
git-tree-sha1 = "0a354c7a5ae8c9beca5d18416095db145a9df28c"
libc = "musl"
os = "linux"

    [[CImGuiPack.download]]
    sha256 = "34925cc0ed818f0e4ccef121b758b87641b0efaaebad71d40f6465d599177097"
    url = "https://github.com/JuliaBinaryWrappers/CImGuiPack_jll.jl/releases/download/CImGuiPack-v0.12.2+0/CImGuiPack.v0.12.2.i686-linux-musl.tar.gz"
[[CImGuiPack]]
arch = "i686"
git-tree-sha1 = "0f6d2de60335e37304129aeb8446d130323ac3fe"
os = "windows"

    [[CImGuiPack.download]]
    sha256 = "6a74885b28197977bc27c693001f8e62be621409ead46629c48bcacef8f4a76f"
    url = "https://github.com/JuliaBinaryWrappers/CImGuiPack_jll.jl/releases/download/CImGuiPack-v0.12.2+0/CImGuiPack.v0.12.2.i686-w64-mingw32.tar.gz"
[[CImGuiPack]]
arch = "powerpc64le"
git-tree-sha1 = "a7a83ef0ee4b6e51744c8dbecde9e069e1aa9d84"
libc = "glibc"
os = "linux"

    [[CImGuiPack.download]]
    sha256 = "b78934435c34eec43dd720c131d155f0d993ff134f3e9a08a25d1a00fece445e"
    url = "https://github.com/JuliaBinaryWrappers/CImGuiPack_jll.jl/releases/download/CImGuiPack-v0.12.2+0/CImGuiPack.v0.12.2.powerpc64le-linux-gnu.tar.gz"
[[CImGuiPack]]
arch = "x86_64"
git-tree-sha1 = "298fae14fb235b0be74422b7b378e1a990ac2197"
os = "macos"

    [[CImGuiPack.download]]
    sha256 = "59f4ed48ac691d7a8c963e861c7ab3bcf15d97b787f834188d2210dec595d672"
    url = "https://github.com/JuliaBinaryWrappers/CImGuiPack_jll.jl/releases/download/CImGuiPack-v0.12.2+0/CImGuiPack.v0.12.2.x86_64-apple-darwin.tar.gz"
[[CImGuiPack]]
arch = "x86_64"
git-tree-sha1 = "25f85881eb5cd886b4b5e3b1a911e6d902a75b4e"
libc = "glibc"
os = "linux"

    [[CImGuiPack.download]]
    sha256 = "620af820ae9d7aedc55956fdfe41f6da6f465dd1e619c9dac1b2849d92db0281"
    url = "https://github.com/JuliaBinaryWrappers/CImGuiPack_jll.jl/releases/download/CImGuiPack-v0.12.2+0/CImGuiPack.v0.12.2.x86_64-linux-gnu.tar.gz"
[[CImGuiPack]]
arch = "x86_64"
git-tree-sha1 = "b62e9cab2d9bea694d960eb6d545d02d86ee5248"
libc = "musl"
os = "linux"

    [[CImGuiPack.download]]
    sha256 = "9ecab7e7bec9b2229011c1f0227949ffe7c556d87209360476e1b472a381d9eb"
    url = "https://github.com/JuliaBinaryWrappers/CImGuiPack_jll.jl/releases/download/CImGuiPack-v0.12.2+0/CImGuiPack.v0.12.2.x86_64-linux-musl.tar.gz"
[[CImGuiPack]]
arch = "x86_64"
git-tree-sha1 = "027f27430ed6c1d512a65a108eba6540312fd05b"
os = "freebsd"

    [[CImGuiPack.download]]
    sha256 = "5bf65db7c5e9f94ce26d4064806a88d8397d968f958bffbe7227f63a0c071a83"
    url = "https://github.com/JuliaBinaryWrappers/CImGuiPack_jll.jl/releases/download/CImGuiPack-v0.12.2+0/CImGuiPack.v0.12.2.x86_64-unknown-freebsd.tar.gz"
[[CImGuiPack]]
arch = "x86_64"
git-tree-sha1 = "6276d175e56ba92e85360c74956c654976b8c172"
os = "windows"

    [[CImGuiPack.download]]
    sha256 = "86025d8c8c648eee9a338329704f08bc28aaa5c29c829b5595eba3340c307740"
    url = "https://github.com/JuliaBinaryWrappers/CImGuiPack_jll.jl/releases/download/CImGuiPack-v0.12.2+0/CImGuiPack.v0.12.2.x86_64-w64-mingw32.tar.gz"
