[[CImGuiPack]]
arch = "aarch64"
git-tree-sha1 = "4aca0f11428c3a2e42c87efec0ef5786ffc0057e"
os = "macos"

    [[CImGuiPack.download]]
    sha256 = "b262e6a18aee7999c22f4354aa28cd7d29cdb5ed53ac5bef48242a01798a44f9"
    url = "https://github.com/JuliaBinaryWrappers/CImGuiPack_jll.jl/releases/download/CImGuiPack-v0.2.0+0/CImGuiPack.v0.2.0.aarch64-apple-darwin.tar.gz"
[[CImGuiPack]]
arch = "aarch64"
git-tree-sha1 = "bbdbc83d198a7d870f097c0121f10c55d5166c00"
libc = "glibc"
os = "linux"

    [[CImGuiPack.download]]
    sha256 = "00e709e56a2b1a7d2f924410bc2eeba741f34bf9beb5ab83e5e397c491a85b45"
    url = "https://github.com/JuliaBinaryWrappers/CImGuiPack_jll.jl/releases/download/CImGuiPack-v0.2.0+0/CImGuiPack.v0.2.0.aarch64-linux-gnu.tar.gz"
[[CImGuiPack]]
arch = "aarch64"
git-tree-sha1 = "a57d0670d8b7b2371c6ebaf1c4028b1b213d60eb"
libc = "musl"
os = "linux"

    [[CImGuiPack.download]]
    sha256 = "34e552cfcc7e11f4f9ac37b3f815a9ff0527b20b15d1e2349f6a8a0722a0a3aa"
    url = "https://github.com/JuliaBinaryWrappers/CImGuiPack_jll.jl/releases/download/CImGuiPack-v0.2.0+0/CImGuiPack.v0.2.0.aarch64-linux-musl.tar.gz"
[[CImGuiPack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "165777ad5ebb5e787c7271ab82c565b0b1036c91"
libc = "glibc"
os = "linux"

    [[CImGuiPack.download]]
    sha256 = "eca7998ab71df1bb862844902556eb90281b9fed0905d9c3db8d9b0ce1d03252"
    url = "https://github.com/JuliaBinaryWrappers/CImGuiPack_jll.jl/releases/download/CImGuiPack-v0.2.0+0/CImGuiPack.v0.2.0.armv6l-linux-gnueabihf.tar.gz"
[[CImGuiPack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "08fef792f7dbd1fe2ce32d211f8e5b494c7f3af4"
libc = "musl"
os = "linux"

    [[CImGuiPack.download]]
    sha256 = "556ee2156910e140296ba9fd3f188f2150f10afe66486277c3e6131a57a88d1d"
    url = "https://github.com/JuliaBinaryWrappers/CImGuiPack_jll.jl/releases/download/CImGuiPack-v0.2.0+0/CImGuiPack.v0.2.0.armv6l-linux-musleabihf.tar.gz"
[[CImGuiPack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d9313a7003f7a30dfbc33f2b46666a242c05786b"
libc = "glibc"
os = "linux"

    [[CImGuiPack.download]]
    sha256 = "205ddfb2d350b6b4de766e73a5104e3b6aa707360faba5d459bffe8e4f60268c"
    url = "https://github.com/JuliaBinaryWrappers/CImGuiPack_jll.jl/releases/download/CImGuiPack-v0.2.0+0/CImGuiPack.v0.2.0.armv7l-linux-gnueabihf.tar.gz"
[[CImGuiPack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f66fa0bd94acef4a1e6a41296d66aaae1bc666b4"
libc = "musl"
os = "linux"

    [[CImGuiPack.download]]
    sha256 = "c91db24d9300687444b48b009aefc4d5b4ec6c211f94923c8c3ce3547c40dfdf"
    url = "https://github.com/JuliaBinaryWrappers/CImGuiPack_jll.jl/releases/download/CImGuiPack-v0.2.0+0/CImGuiPack.v0.2.0.armv7l-linux-musleabihf.tar.gz"
[[CImGuiPack]]
arch = "i686"
git-tree-sha1 = "0669f9e93677b0d44b1a6a9ba031fb6bb65c3746"
libc = "glibc"
os = "linux"

    [[CImGuiPack.download]]
    sha256 = "029c04011e408db3615df2c97323959aa63b50f01482bd474c06af34434672fd"
    url = "https://github.com/JuliaBinaryWrappers/CImGuiPack_jll.jl/releases/download/CImGuiPack-v0.2.0+0/CImGuiPack.v0.2.0.i686-linux-gnu.tar.gz"
[[CImGuiPack]]
arch = "i686"
git-tree-sha1 = "f7e442b6988c8984d52c2f12e9cb15bf9896328b"
libc = "musl"
os = "linux"

    [[CImGuiPack.download]]
    sha256 = "c015833f5b07887239457220fd79ba159b6009eb286784050bf86a4ee8c042a3"
    url = "https://github.com/JuliaBinaryWrappers/CImGuiPack_jll.jl/releases/download/CImGuiPack-v0.2.0+0/CImGuiPack.v0.2.0.i686-linux-musl.tar.gz"
[[CImGuiPack]]
arch = "i686"
git-tree-sha1 = "66ca70a7ed7bd035b7de308ac7f88822159ee239"
os = "windows"

    [[CImGuiPack.download]]
    sha256 = "f9d669253c2e4e7a48cc2ce4c3672e86c9f50d9bc8071df9216e97e3228d5378"
    url = "https://github.com/JuliaBinaryWrappers/CImGuiPack_jll.jl/releases/download/CImGuiPack-v0.2.0+0/CImGuiPack.v0.2.0.i686-w64-mingw32.tar.gz"
[[CImGuiPack]]
arch = "powerpc64le"
git-tree-sha1 = "a0979499cc13d0856192a04ff2d6bdcb1d31f694"
libc = "glibc"
os = "linux"

    [[CImGuiPack.download]]
    sha256 = "c59ad69db1644cdc0400224b750d1fb70646da6cdfae1fd176abcd2de12accc7"
    url = "https://github.com/JuliaBinaryWrappers/CImGuiPack_jll.jl/releases/download/CImGuiPack-v0.2.0+0/CImGuiPack.v0.2.0.powerpc64le-linux-gnu.tar.gz"
[[CImGuiPack]]
arch = "x86_64"
git-tree-sha1 = "e5d6178e96f4e9f16d8fd8858d04dee591376340"
os = "macos"

    [[CImGuiPack.download]]
    sha256 = "2c3f9adb8910f1892146a72fa771bbb5313161e013ff8dfda5ee9762982b35c7"
    url = "https://github.com/JuliaBinaryWrappers/CImGuiPack_jll.jl/releases/download/CImGuiPack-v0.2.0+0/CImGuiPack.v0.2.0.x86_64-apple-darwin.tar.gz"
[[CImGuiPack]]
arch = "x86_64"
git-tree-sha1 = "fe48f0b2aafb29660aa25ab0e55249169fabee58"
libc = "glibc"
os = "linux"

    [[CImGuiPack.download]]
    sha256 = "11a2614c143cfb6652843b24a6bdd58149fe29dde6611cd507aacb05129f4a18"
    url = "https://github.com/JuliaBinaryWrappers/CImGuiPack_jll.jl/releases/download/CImGuiPack-v0.2.0+0/CImGuiPack.v0.2.0.x86_64-linux-gnu.tar.gz"
[[CImGuiPack]]
arch = "x86_64"
git-tree-sha1 = "89cef2434c29fbee1d1e6c6d09d5785bd236f277"
libc = "musl"
os = "linux"

    [[CImGuiPack.download]]
    sha256 = "ead3478a4308bdf36c8ada36fd8b72d5d7ff9ba87ffc381a0d071c1db0da61cb"
    url = "https://github.com/JuliaBinaryWrappers/CImGuiPack_jll.jl/releases/download/CImGuiPack-v0.2.0+0/CImGuiPack.v0.2.0.x86_64-linux-musl.tar.gz"
[[CImGuiPack]]
arch = "x86_64"
git-tree-sha1 = "ea1660a87c49720b2b0f8cb1986b0d8e1e9bff4e"
os = "freebsd"

    [[CImGuiPack.download]]
    sha256 = "59e8c5e613d02eca1c59e67bc08af1befb6aa6c25276227492cd67cce84d04ed"
    url = "https://github.com/JuliaBinaryWrappers/CImGuiPack_jll.jl/releases/download/CImGuiPack-v0.2.0+0/CImGuiPack.v0.2.0.x86_64-unknown-freebsd.tar.gz"
[[CImGuiPack]]
arch = "x86_64"
git-tree-sha1 = "27ef50bab46adeedd512c09d3e6ee063ba1da615"
os = "windows"

    [[CImGuiPack.download]]
    sha256 = "c87be683b9abe0e44115341a93d0a3d61584c27b44538b234e43f8f1c7e9e422"
    url = "https://github.com/JuliaBinaryWrappers/CImGuiPack_jll.jl/releases/download/CImGuiPack-v0.2.0+0/CImGuiPack.v0.2.0.x86_64-w64-mingw32.tar.gz"
